Removed historie and updated to Nuxt3 RC 13
sidebase/sidebase pull request #75
Opened 2022-11-14 16:04 UTC by zoey-kaiser

Closes #50 

The upgrade and removal of historie went successfully. However afterwards I have now run into the issue that the type `CompatibilityEvent` and `CompatibilityEventHandler` do not exist within the `h3` package. I did some googling about these types and also found no documentation on them. Any tips @BracketJohn?

![Screenshot 2022-11-14 at 17 02 28](https://user-images.githubusercontent.com/30908158/201707624-68c49e43-68b7-492c-bf9b-1f796adafb9c.png)

2022-11-14 16:10 UTC, BracketJohn commented
try `H3Event`! It superceeded `CompabitlityEvent`, which was deprecated.

Please make sure to go through the recent 3 releases and adapt our code to all changes that you can find. E.g., this change is a bit hidden as part of rc.12. To find it you have to see that:
- breaking h3 upgrade announced as part of release notes: https://github.com/nuxt/framework/releases/tag/v3.0.0-rc.12
- the h3 release notes say to use `eventHandler`, which has a different event type: https://github.com/unjs/h3/releases/tag/v0.8.0

2022-11-14 17:21 UTC, BracketJohn commented
ok so tbh my starting point would be: ditch the way we've written api tests until now and introduce https://v3.nuxtjs.org/getting-started/testing -> this is also a recent additon and would allow us to strip supertest, a lot of the hacky setup files, ... from this starter. Do you think you're up for the challenge?

2022-11-14 17:22 UTC, zoey-kaiser commented
> ok so tbh my starting point would be: ditch the way we've written api tests until now and introduce https://v3.nuxtjs.org/getting-started/testing -> this is also a recent additon and would allow us to strip supertest, a lot of the hacky setup files, ... from this starter. Do you think you're up for the challenge?

Ill take a shot at it right now! If I notice that I am struggling I will let you know in the morning and we should still have enough time to finish this PR!

2022-11-15 07:12 UTC, BracketJohn commented
I've had a look at this.

First I also tried leanly to use native-nuxt-testing, but this always failed with INVALID URL SCHEME, I had an approach to solve this by checking all used URIs, but this approach is indeterministic and may take some time.

So I then switched to actually resolving the current problem without introducing big changes: That was easy -> the error is `app.address() is undefined`. This is due to `.address()` only existing on a node-app, not on an h3-app. This must've existed in the past but then removed with one of the latest releases. Checking out their own tests, we see how they resolve it: wrap app in `toNodeListener(app)`, see https://github.com/unjs/h3/blob/501f0c6e623ea827d47691046f3c7319f5ac4651/test/proxy.test.ts

Tests are passing now 🎊

2022-11-15 07:21 UTC, BracketJohn commented on server/api/example/[id].get.ts
> +export default defineEventHandler(async (event: H3Event) => {
let's also use `eventHandler` instead of `defineEventHandler`, as written here: https://github.com/unjs/h3/releases

2022-11-15 14:40 UTC, BracketJohn approved these changes

2022-11-15 14:44 UTC, BracketJohn requested changes
The following does not work, please fix ASAP
```sh
❯ npm run build

> build
> nuxi build

Nuxi 3.0.0-rc.13                                                                                                                                                                                            15:42:41
Nuxt 3.0.0-rc.13 with Nitro 0.6.1                                                                                                                                                                           15:42:41
ℹ Using default Tailwind CSS file from runtime/tailwind.css                                                                                                                                nuxt:tailwindcss 15:42:42
ℹ Client built in 3470ms                                                                                                                                                                                    15:42:46
ℹ Building server...                                                                                                                                                                                        15:42:46
✔ Server built in 2930ms                                                                                                                                                                                    15:42:49
✔ Generated public .output/public                                                                                                                                                                     nitro 15:42:49
ℹ Building Nitro Server (preset: node-server)                                                                                                                                                         nitro 15:42:49

 WARN  Multiple major versions of package supports-color are being externalized. Picking latest version:                                                                                                    15:42:52

  + /Users/nils/repos/sidebase/sidebase/node_modules/typeorm/node_modules/supports-color@7.2.0
  - /Users/nils/repos/sidebase/sidebase/node_modules/supports-color@5.5.0


 WARN  Multiple major versions of package parse5 are being externalized. Picking latest version:                                                                                                            15:42:52

  - /Users/nils/repos/sidebase/sidebase/node_modules/cli-highlight/node_modules/parse5@5.1.1
  + /Users/nils/repos/sidebase/sidebase/node_modules/parse5-htmlparser2-tree-adapter/node_modules/parse5@6.0.1


 WARN  Multiple major versions of package parse5 are being externalized. Picking latest version:                                                                                                            15:42:52

  + /Users/nils/repos/sidebase/sidebase/node_modules/parse5-htmlparser2-tree-adapter/node_modules/parse5@6.0.1
  - /Users/nils/repos/sidebase/sidebase/node_modules/cli-highlight/node_modules/parse5@5.1.1


 WARN  Multiple major versions of package has-flag are being externalized. Picking latest version:                                                                                                          15:42:52

  + /Users/nils/repos/sidebase/sidebase/node_modules/typeorm/node_modules/has-flag@4.0.0
  - /Users/nils/repos/sidebase/sidebase/node_modules/has-flag@3.0.0


 WARN  Multiple major versions of package semver are being externalized. Picking latest version:                                                                                                            15:42:52

  + /Users/nils/repos/sidebase/sidebase/node_modules/@mapbox/node-pre-gyp/node_modules/semver@7.3.8
  - /Users/nils/repos/sidebase/sidebase/node_modules/semver@6.3.0


 WARN  Multiple major versions of package npmlog are being externalized. Picking latest version:                                                                                                            15:42:52

  - /Users/nils/repos/sidebase/sidebase/node_modules/npmlog@5.0.1
  + /Users/nils/repos/sidebase/sidebase/node_modules/node-gyp/node_modules/npmlog@6.0.2


 WARN  Multiple major versions of package are-we-there-yet are being externalized. Picking latest version:                                                                                                  15:42:52

  - /Users/nils/repos/sidebase/sidebase/node_modules/are-we-there-yet@2.0.0
  + /Users/nils/repos/sidebase/sidebase/node_modules/node-gyp/node_modules/are-we-there-yet@3.0.1


 WARN  Multiple major versions of package gauge are being externalized. Picking latest version:                                                                                                             15:42:52

  - /Users/nils/repos/sidebase/sidebase/node_modules/gauge@3.0.2
  + /Users/nils/repos/sidebase/sidebase/node_modules/node-gyp/node_modules/gauge@4.0.4

✔ Nitro server built                                                                                                                                                                                  nitro 15:42:52
  ├─ .output/server/package.json (3.35 kB) (1.26 kB gzip)
  ├─ .output/server/index.mjs (572 B) (302 B gzip)
  ├─ .output/server/chunks/nitro/node-server.mjs.map (83.4 kB) (6.32 kB gzip)
  ├─ .output/server/chunks/nitro/node-server.mjs (25.6 kB) (7.55 kB gzip)
  ├─ .output/server/chunks/index.mjs.map (277 B) (192 B gzip)
  ├─ .output/server/chunks/index.mjs (693 B) (355 B gzip)
  ├─ .output/server/chunks/healthz.get.mjs.map (602 B) (320 B gzip)
  ├─ .output/server/chunks/healthz.get.mjs (997 B) (528 B gzip)
  ├─ .output/server/chunks/handlers/renderer.mjs.map (19.8 kB) (3.44 kB gzip)
  ├─ .output/server/chunks/handlers/renderer.mjs (15.9 kB) (4.91 kB gzip)
  ├─ .output/server/chunks/error-500.mjs.map (1.06 kB) (379 B gzip)
  ├─ .output/server/chunks/error-500.mjs (4.26 kB) (1.83 kB gzip)
  ├─ .output/server/chunks/app/styles.mjs.map (383 B) (217 B gzip)
  ├─ .output/server/chunks/app/styles.mjs (420 B) (243 B gzip)
  ├─ .output/server/chunks/app/server.mjs.map (45.8 kB) (6.97 kB gzip)
  ├─ .output/server/chunks/app/server.mjs (37.9 kB) (9.6 kB gzip)
  ├─ .output/server/chunks/app/client.manifest.mjs.map (2.49 kB) (486 B gzip)
  ├─ .output/server/chunks/app/client.manifest.mjs (3.37 kB) (612 B gzip)
  ├─ .output/server/chunks/app/_nuxt/index.208c0c95.mjs.map (269 kB) (44.1 kB gzip)
  ├─ .output/server/chunks/app/_nuxt/index.208c0c95.mjs (253 kB) (55.3 kB gzip)
  ├─ .output/server/chunks/app/_nuxt/error-component.e499347b.mjs.map (2.35 kB) (803 B gzip)
  ├─ .output/server/chunks/app/_nuxt/error-component.e499347b.mjs (2.01 kB) (894 B gzip)
  ├─ .output/server/chunks/app/_nuxt/error-500.5a83d237.mjs.map (1.7 kB) (613 B gzip)
  ├─ .output/server/chunks/app/_nuxt/error-500.5a83d237.mjs (3.32 kB) (1.46 kB gzip)
  ├─ .output/server/chunks/app/_nuxt/error-500-styles.ad145178.mjs.map (366 B) (224 B gzip)
  ├─ .output/server/chunks/app/_nuxt/error-500-styles.ad145178.mjs (2.22 kB) (864 B gzip)
  ├─ .output/server/chunks/app/_nuxt/error-404.1a84ca10.mjs.map (2.34 kB) (786 B gzip)
  ├─ .output/server/chunks/app/_nuxt/error-404.1a84ca10.mjs (4.17 kB) (1.75 kB gzip)
  ├─ .output/server/chunks/app/_nuxt/error-404-styles.3db9fdd2.mjs.map (366 B) (224 B gzip)
  ├─ .output/server/chunks/app/_nuxt/error-404-styles.3db9fdd2.mjs (3.92 kB) (1.25 kB gzip)
  ├─ .output/server/chunks/_id_.patch.mjs.map (717 B) (358 B gzip)
  ├─ .output/server/chunks/_id_.patch.mjs (1.08 kB) (507 B gzip)
  ├─ .output/server/chunks/_id_.get.mjs.map (540 B) (302 B gzip)
  └─ .output/server/chunks/_id_.get.mjs (874 B) (448 B gzip)
Σ Total size: 13.7 MB (4.03 MB gzip)
✔ You can preview this build using node .output/server/index.mjs

❯ npm run start

> start
> NODE_ENV=production node .output/server/index.mjs

node:internal/modules/cjs/loader:353
      const err = new Error(
                  ^

Error: Cannot find module '/Users/nils/repos/sidebase/sidebase/.output/server/node_mod [...]

2022-11-15 15:17 UTC, zoey-kaiser commented
> one solution can be to install explicit versions of the problematic package (here: parse5). It would be nice to find a nicer solution / the actual cause for this though.

I tried installing `parse5`, but the error still occurs!

2022-11-15 15:54 UTC, zoey-kaiser commented
I have also attempted to regenerate the `package-lock.json`, but it sadly did not resolve the issue as well.

2022-11-15 16:26 UTC, valiafetisov commented
Fresh installation of npm packages worked for me. Am I missing something here?
```
$ git show --summary
commit 693ad97755779c58923cbdcdaf7388f3ac7a2645 (HEAD -> remove-historie, origin/remove-historie)
Author: Zoey Kaiser <zoeykaiser8@gmail.com>
Date:   Tue Nov 15 11:16:46 2022 +0100

    Changed defineEventHandler to eventHandler

$ rm -rf node_modules
$ npm i
$ npm run build

> build
> nuxi build

Nuxi 3.0.0-rc.13                                                      17:22:24
Nuxt 3.0.0-rc.13 with Nitro 0.6.1                                     17:22:24
ℹ Using default Tailwind CSS file from runtime/tailwind.css
ℹ Client built in 3618ms                                              17:22:29
ℹ Building server...                                                  17:22:29
✔ Server built in 3124ms                                              17:22:32
✔ Generated public .output/public                               nitro 17:22:32
ℹ Building Nitro Server (preset: node-server)                   nitro 17:22:32

 WARN  Multiple major versions of package supports-color are being externalized. Picking latest version:

  + /Users/user/Projects/sidestream/sidebase/node_modules/typeorm/node_modules/supports-color@7.2.0
  - /Users/user/Projects/sidestream/sidebase/node_modules/supports-color@5.5.0


 WARN  Multiple major versions of package parse5 are being externalized. Picking latest version:

  - /Users/user/Projects/sidestream/sidebase/node_modules/cli-highlight/node_modules/parse5@5.1.1
  + /Users/user/Projects/sidestream/sidebase/node_modules/parse5-htmlparser2-tree-adapter/node_modules/parse5@6.0.1


 WARN  Multiple major versions of package parse5 are being externalized. Picking latest version:

  + /Users/user/Projects/sidestream/sidebase/node_modules/parse5-htmlparser2-tree-adapter/node_modules/parse5@6.0.1
  - /Users/user/Projects/sidestream/sidebase/node_modules/cli-highlight/node_modules/parse5@5.1.1


 WARN  Multiple major versions of package has-flag are being externalized. Picking latest version:

  + /Users/user/Projects/sidestream/sidebase/node_modules/typeorm/node_modules/has-flag@4.0.0
  - /Users/user/Projects/sidestream/sidebase/node_modules/has-flag@3.0.0


 WARN  Multiple major versions of package semver are being externalized. Picking latest version:

  + /Users/user/Projects/sidestream/sidebase/node_modules/@mapbox/node-pre-gyp/node_modules/semver@7.3.8
  - /Users/user/Projects/sidestream/sidebase/node_modules/semver@6.3.0


 WARN  Multiple major versions of package npmlog are being externalized. Picking latest version:

  - /Users/user/Projects/sidestream/sidebase/node_modules/npmlog@5.0.1
  + /Users/user/Projects/sidestream/sidebase/node_modules/node-gyp/node_modules/npmlog@6.0.2


 WARN  Multiple major versions of package are-we-there-yet are being externalized. Picking latest version:

  - /Users/user/Projects/sidestream/sidebase/node_modules/are-we-there-yet@2.0.0
  + /Users/user/Projects/sidestream/sidebase/node_modules/node-gyp/node_modules/are-we-there-yet@3.0.1


 WARN  Multiple major versions of package gauge are being externalized. Picking latest version:

  - /Users/user/Projects/sidestream/sidebase/node_modules/gauge@3.0.2
  + /Users/user/Projects/sidestream/sidebase/node_modules/node-gyp/node_modules/gauge@4.0.4

✔ Nitro server built                                            nitro 17:22:36
  ├─ .output/server/package.json (3.35 kB) (1.26 kB gzip)
  ├─ .output/server/index.mjs (572 B) (302 B gzip)
  ├─ .output/server/chunks/nitro/node-server.mjs.map (83.5 kB) (6.33 kB gzip)
  ├─ .output/server/chunks/nitro/node-server.mjs (25.6 kB) (7.56 kB gzip)
  ├─ .output/server/chunks/index.mjs.map (282 B) (199 B gzip)
  ├─ .output/server/chunks/index.mjs (693 B) (355 B gzip)
  ├─ .output/server/chunks/healthz.get.mjs.map (607 B) (327 B gzip)
  ├─ .output/server/chunks/healthz.get.mjs (997 B) (528 B gzip)
  ├─ .output/server/chunks/handlers/renderer.mjs.map (19.8 kB) (3.45 kB gzip)
  ├─ .output/server/chunks/handlers/renderer.mjs (15.9 kB) (4.91 kB gzip)
  ├─ .output/server/chunks/error-500.mjs.map (1.06 kB) (387 B gzip)
  ├─ .output/server/chunks/error-500.mjs (4.26 kB) (1.83 kB gzip)
  ├─ .output/server/chunks/app/styles.mjs.map (388 B) (224 B gzip)
  ├─ .output/server/chunks/app/styles.mjs (420 B) (243 B gzip)
  ├─ .output/server/chunks/app/server.mjs.map (45.8 kB) (6.97 kB gzip)
  ├─ .output/server/chunks/app/server.mjs (37.9 kB) (9.61 kB gzip)
  ├─ .output/server/chunks/app/client.manifest.mjs.map (2.5 kB) (491 B gzip)
  ├─ .output/server/chunks/app/client.manifest.mjs (3.39 kB) (619 B gzip)
  ├─ .output/server/chunks/app/_nuxt/index.ac1371dc.mjs.map (269 kB) (44.1 kB gzip)
  ├─ .output/server/chunks/app/_nuxt/index.ac1371dc.mjs (253 kB) (55.3 kB gzip)
  ├─ .output/server/chunks/app/_nuxt/error-component.a04b1df1.mjs.map (2.35 kB) (810 B gzip)
  ├─ .output/server/chunks/app/_nuxt/error-component.a04b1df1.mjs (2.01 kB) (894 B gzip)
  ├─ .output/server/chunks/app/_nuxt/error-500.bcaa8724.mjs.map (1.71 kB) (620 B gzip)
  ├─ .output/server/chunks/app/_nuxt/error-500.bcaa8724.mjs (3.32 kB) (1.46 kB gzip)
  ├─ .output/server/chunks/app/_nuxt/error-500-styles.ad145178.mjs.map (376 B) (231 B gzip)
  ├─ .output/server/chunks/app/_nuxt/error-500-styles.ad145178.mjs (2.22 kB) (864 B gzip)
  ├─ .output/server/chunks/app/_nuxt/error-404.87cd941e.mjs.map (2.35 kB) (793 B gzip)
  ├─ .output/server/chunks/app/_nuxt/error-404.87cd941e.mjs (4.17 kB) (1.75 kB gzip)
  ├─ .output/server/chunks/app/_nuxt/error-404-styles.3db9fdd2.mjs.map (376 B) (231 B gzip)
  ├─ .output/server/chunks/app/_nuxt/error-404-styles.3db9fdd2.mjs (3.92 kB) (1.25 kB gzip)
  ├─ .output/server/chunks/_id_.patch.mjs.map (722 B) (365 B gzip)
  ├─ .output/server/chunks/_id_.patch.mjs (1.08 kB) (507 B gzip)
  ├─ .output/server/chunks/_id_.get.mjs.map (545 B) (308 B gzip)
  └─ .output/server/chunks/_id_.get.mjs (874 B) (448 B gzip)
Σ Total size: 13.7 MB (4.03 MB gzip)
✔ You can preview this build using node .output/server/index.mjs

2022-11-15 17:47 UTC, valiafetisov commented
Maybe https://stackoverflow.com/a/74213192 will help nitro to properly build?

2022-11-15 18:50 UTC, zoey-kaiser commented
> One other think we can try, is to upgrade to RC14 which is not yet published but prepared in a branch in the hopes that it is fixed there.

I upgraded to the edge channel of RC14, but it sadly also did not resolve our issue 😢

2022-11-16 10:38 UTC, zoey-kaiser commented
> Maybe https://stackoverflow.com/a/74213192 will help nitro to properly build?

I have also attempted to add this solution to our `package.json`. While it did resolve the first error (maybe) it threw a new error:

```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/common/doctype' is not defined by "exports" in /Users/zoey/Documents/Development/SideStream/sidebase/sidebase/.output/server/node_modules/parse5/package.json
    at new NodeError (node:internal/errors:387:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:464:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:748:3)
    at resolveExports (node:internal/modules/cjs/loader:493:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:533:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:942:27)
    at Function.Module._load (node:internal/modules/cjs/loader:804:27)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/zoey/Documents/Development/SideStream/sidebase/sidebase/.output/server/node_modules/parse5-htmlparser2-tree-adapter/lib/index.js:3:17) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```

Is this error easier to make sense of? For me it looks similar to the last one (in the sense of it not finsing specific files that should be included in the package.

2022-11-20 12:41 UTC, BracketJohn commented
Digging into this:
1. remove most files and directories (server, components, pages, ....)
2. try out `npm run build && npm run start` -> it works again
3. subsequently add back files using git, e.g., `git checkout -- components/`
4. figure out that it re-appears as soon as we add something that imports something from typeorm, e.g., the init plugin
5. check if conflicting deps of build step occure in typeorm -> `npm ls parse5` yields conflicting parse5-results for typeorm + one more for another package
6. use npm `override` field to fix dep to higher of the two only for typeorm -> It works 🎊 


Here's the override:
```
  "overrides": {
    "typeorm": {
      "parse5": "6.0.1"
    }
  },
```

This solution works for `npm` and `pnpm`. Yarn users will / may have problems with it 😢 I think for now this is ok until someone complains. I've added a small note to the readme about this.

2022-11-20 12:42 UTC, BracketJohn approved these changes

2022-11-20 12:44 UTC, merged

2022-11-25 14:28 UTC, djschilling commented
@BracketJohn the problem still seems to appear. I just followed the getting started guid and `npm run build && npm run start` still gives me this error:

```
npm run start

> start
> NODE_ENV=production node .output/server/index.mjs

node:internal/modules/cjs/loader:364
      const err = new Error(
                  ^

Error: Cannot find module '/Users/david/projects/nuxt-sidebase-app/.output/server/node_modules/parse5/lib/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:364:19)
    at Function.Module._findPath (node:internal/modules/cjs/loader:577:18)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:942:27)
    at Function.Module._load (node:internal/modules/cjs/loader:804:27)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/david/projects/nuxt-sidebase-app/.output/server/node_modules/cli-highlight/dist/index.js:30:27)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32) {
  code: 'MODULE_NOT_FOUND',
  path: '/Users/david/projects/nuxt-sidebase-app/.output/server/node_modules/parse5/package.json',
  requestPath: 'parse5'
}
```

2022-11-25 14:34 UTC, djschilling commented
adding 

```
    "cli-highlight": {
      "parse5": "6.0.1"
    }
```

to the overrides section in package.json fixes it for me.

2022-11-25 17:17 UTC, BracketJohn commented
Hey @djschilling - you're a saviour, thanks for reporting this -> weird how this slipped through 🤔 

I've opened #78 to track this + #79 to resolve this -> can you checkout whether the problem is fixed on #79 for you?

2022-12-02 16:21 UTC, djschilling commented
it ist fixed with this

2022-12-03 11:54 UTC, BracketJohn commented
Perfect, thanks for reporting back @djschilling ❤️